// <auto-generated />
using System;
using IslamicTragemContextHandeling.Core.NewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IslamicTragemContextHandeling.Core.Migrations
{
    [DbContext(typeof(forumisl_quran3Context))]
    [Migration("20251231143936_ChangeColumnNamesAndAddColumnsToFixedPages")]
    partial class ChangeColumnNamesAndAddColumnsToFixedPages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Aya", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AyaNo")
                        .HasColumnType("int");

                    b.Property<string>("AyaNoAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HezbNo")
                        .HasColumnType("int");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<int?>("PartNo")
                        .HasColumnType("int");

                    b.Property<int>("RobaNo")
                        .HasColumnType("int");

                    b.Property<int?>("SuraId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextNoSigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuraId");

                    b.ToTable("Ayas");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsValidForLibrary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidForTerms")
                        .HasColumnType("bit");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.FixedPage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContentAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FixedPages");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Hadith", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BabId")
                        .HasColumnType("int");

                    b.Property<string>("HadithWithNoSign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadithWithSign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BabId");

                    b.ToTable("Hadiths");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithBab", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BabNo")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("HadithBabs");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AboutBook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatNameTakhreej")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ChapterRows")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullWriterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexBook")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SearchOrder")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Sound")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StartId")
                        .HasColumnType("int");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WriterDeath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HadithCategories");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithChapter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNo")
                        .HasColumnType("int");

                    b.Property<int>("HadithCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HadithCategoryId");

                    b.ToTable("HadithChapters");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithLanguage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HadithLanguages");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HadithId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HadithId");

                    b.HasIndex("LanguageId");

                    b.ToTable("HadithTranslations");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.LibraryBook", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("DownloadLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OutSource")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SourceLang")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TargetLang")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Translator")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("LibraryBooks");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.News", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Paper", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdminName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagesNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PaperLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("ResearcherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViewCount")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.HasKey("Id");

                    b.HasIndex("PaperLanguageId");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.PaperLanguage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaperLanguages");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.QuranTranslation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Translation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslatorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("QuranTranslations");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.SpecialistsCenter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Intag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Masarat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("ViewCount")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("WebsiteURL")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SpecialistsCenters");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Sura", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Suras");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Term", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("English")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EnglishSynonyms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("French")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("FrenchSynonyms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MeaningLanguage")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("MeaningTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spanish")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SpanishSynonyms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("VoiceSpell")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Aya", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Sura", "Sura")
                        .WithMany()
                        .HasForeignKey("SuraId");

                    b.Navigation("Sura");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Hadith", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.HadithBab", "Bab")
                        .WithMany()
                        .HasForeignKey("BabId");

                    b.Navigation("Bab");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithBab", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.HadithChapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithChapter", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.HadithCategory", "HadithCategory")
                        .WithMany()
                        .HasForeignKey("HadithCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HadithCategory");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.HadithTranslation", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Hadith", "Hadith")
                        .WithMany()
                        .HasForeignKey("HadithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.HadithLanguage", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hadith");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.LibraryBook", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Paper", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.PaperLanguage", "PaperLanguage")
                        .WithMany()
                        .HasForeignKey("PaperLanguageId");

                    b.Navigation("PaperLanguage");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.QuranTranslation", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aya");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Term", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
