// <auto-generated />
using System;
using IslamicTragemContextHandeling.Core.NewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IslamicTragemContextHandeling.Core.Migrations
{
    [DbContext(typeof(forumisl_quran3Context))]
    [Migration("20251230171332_AddSecondMigrationIndependentTables")]
    partial class AddSecondMigrationIndependentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Aya", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AyaNo")
                        .HasColumnType("int");

                    b.Property<string>("AyaNoAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HezbNo")
                        .HasColumnType("int");

                    b.Property<int?>("PageNo")
                        .HasColumnType("int");

                    b.Property<int?>("PartNo")
                        .HasColumnType("int");

                    b.Property<int>("RobaNo")
                        .HasColumnType("int");

                    b.Property<int?>("SuraId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextNoSigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuraId");

                    b.ToTable("Ayas");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsValidForLibrary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidForTerms")
                        .HasColumnType("bit");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.FixedPage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FixedPages");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.News", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.PaperLanguage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaperLanguages");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.QuranTranslation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AyaId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Translation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslatorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AyaId");

                    b.ToTable("QuranTranslations");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.SpecialistsCenter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Intag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Masarat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("ViewCount")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("WebsiteURL")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SpecialistsCenters");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Sura", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Suras");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.Aya", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Sura", "Sura")
                        .WithMany()
                        .HasForeignKey("SuraId");

                    b.Navigation("Sura");
                });

            modelBuilder.Entity("IslamicTragemContextHandeling.Core.NewModels.QuranTranslation", b =>
                {
                    b.HasOne("IslamicTragemContextHandeling.Core.NewModels.Aya", "Aya")
                        .WithMany()
                        .HasForeignKey("AyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aya");
                });
#pragma warning restore 612, 618
        }
    }
}
