// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("aya", Schema = "forumisl_quran2")]
[OldName("aya")]
public class Aya
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("aya_id")]
    public int? AyaId { get; set; }

    [Required]
    [OldName("aya")]
    public string Aya1 { get; set; }

    [Required]
    [OldName("aya_no_tashkil")]
    public string AyaNoTashkil { get; set; }

    [OldName("page_no")]
    public int? PageNo { get; set; }

    [OldName("part_no")]
    public int? PartNo { get; set; }

    [OldName("hezb_no")]
    public int HezbNo { get; set; }

    [OldName("rob3_no")]
    public int RobaNo { get; set; }

    [OldName("aya_no")]
    public int? AyaNo { get; set; }

    [Required]
    [OldName("aya_no_ar")]
    public string AyaNoAr { get; set; }

    [OldName("sura_no")]
    public int? SuraNo { get; set; }

    [Required]
    [OldName("sura_name")]
    [StringLength(250)]
    public string SuraName { get; set; }

    [OldName("wordCount")]
    public int WordCount { get; set; }

    [OldName("view_count")]
    public int ViewCount { get; set; }
    //public virtual ICollection<QuranTranslation> Translations { get; set; }

}