// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("bab", Schema = "forumisl_quran2")]
[OldName("bab")]
public partial class Bab 
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("chapter_id")]
    public int ChapterId { get; set; } // references chapter(chapterId)

    [OldName("cat_id")]
    public int CatId { get; set; } // references cats(id)

    [Required]
    [OldName("name")]
    public string Name { get; set; }

    //[Required]
    //[OldName("name_new")]
    //[StringLength(1000)]
    //public string NameNew { get; set; }

    [OldName("bab_id")]
    public int BabId { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }

    [OldName("sub_id")]
    public int SubId { get; set; }

    [OldName("cron")]
    public int Cron { get; set; } // 0 or 1 ? what is this for?

    [Required]
    [OldName("sound")]
    [StringLength(255)]
    public string Sound { get; set; }

    //[Required]
    //[OldName("video")]
    //[StringLength(255)]
    //public string Video { get; set; }

    //[ForeignKey(nameof(CatId))]
    //public virtual Cats Cat { get; set; }
    //[ForeignKey(nameof(ChapterId))]
    //public Chapter Chapter { get; set; }
}
 