// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("bab", Schema = "forumisl_quran2")]
public  class Bab
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("name_new")]
    [StringLength(1000)]
    public string NameNew { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("sub_id")]
    public int SubId { get; set; }

    [Column("cron")]
    public int Cron { get; set; }

    [Required]
    [Column("sound")]
    [StringLength(255)]
    public string Sound { get; set; }

    [Required]
    [Column("video")]
    [StringLength(255)]
    public string Video { get; set; }
}