// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("cat", Schema = "forumisl_quran2")]
[OldName("cat")]
public partial class Cat
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("title_en")]
    [StringLength(100)]
    public string TitleEn { get; set; }

    [OldName("title_ar")]
    [StringLength(100)]
    public string TitleAr { get; set; }

    //[OldName("description")]
    //[StringLength(1000)]
    //public string Description { get; set; }
    //public virtual ICollection<Term> Terms { get; set; }
}