// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


namespace IslamicTragemContextHandeling.Core.NewModels;
[OldName("cat")]
public  class Category 
// this is for the library in the home page
// i found that this is used in  categorizing the books 
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("title_en")]
    [StringLength(100)]
    public string TitleEn { get; set; }

    [OldName("title_ar")]
    [StringLength(100)]
    public string TitleAr { get; set; }

    public bool IsValidForLibrary { get; set; }
    public bool IsValidForTerms { get; set; }

}