// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("chapters_muslim", Schema = "forumisl_quran2")]
[Index("CatId", Name = "hadith_bab_id_idx")]
[OldName("chapters_muslim")]
public  class ChaptersMuslim
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [OldName("cat_id")]
    public int CatId { get; set; } // reffers to Cats.id

    //[OldName("tags")]
    //[StringLength(255)]
    //public string Tags { get; set; }

    [OldName("chapter_id")]
    public int ChapterId { get; set; } // reffers to Chapter.ChapterId

    //    [OldName("my_sort")]
    //    public int MySort { get; set; }

    //    [OldName("status")]
    //    public int Status { get; set; }

    //    [OldName("cron")]
    //    public int Cron { get; set; }
    //[ForeignKey(nameof(CatId))]
    //public virtual Cat Cat { get; set; }

 
    //public virtual Chapter Chapter { get; set; }
}