// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("chapters", Schema = "forumisl_quran2")]
[Index("CatId", Name = "hadith_bab_id_idx")]
[OldName("chapters")]
public  class Chapter
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [OldName("cat_id")]
    public int CatId { get; set; } // reffers to Cats.id

    //[OldName("tags")]
    //[StringLength(255)]
    //public string Tags { get; set; }

    [OldName("chapter_id")]
    public int ChapterId { get; set; } // reffers to chapter.ChapterId

    //[OldName("my_sort")]
    //public int MySort { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }

    //[OldName("cron")]
    //public int Cron { get; set; }
    //[ForeignKey(nameof(CatId))]
    //public Cats Cat { get; set; }
    //[ForeignKey(nameof(ChapterId))]
    //public Chapter ParentChapter { get; set; }
    //public virtual ICollection<ChaptersMuslim> MuslimChapters { get; set; }
    //public virtual ICollection<ChaptersBokhary> BokharyChapters { get; set; }
    //public virtual ICollection<Bab> Babs { get; set; }

}