// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("fixed_pages")]
public class FixedPage 
{
    //it containes about us page and the rest of rows are useless
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("title")]
    public string Title { get; set; }

    [Required]
    [OldName("data")]
    public string Data { get; set; } 

    [Required]
    [OldName("data_en")]
    public string DataEn { get; set; } 

}