// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("fixed_pages", Schema = "forumisl_quran2")]
public  class FixedPage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Required]
    [Column("data")]
    public string Data { get; set; }

    [Required]
    [Column("data_en")]
    public string DataEn { get; set; }

    [Column("status")]
    public int Status { get; set; }
}