// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

public  class forumisl_quran3Context : DbContext
{
    public forumisl_quran3Context()
    {
    }

    public forumisl_quran3Context(DbContextOptions<forumisl_quran3Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Sura> Suras { get; set; }
    public virtual DbSet<Aya> Ayas { get; set; }
    public virtual DbSet<QuranTranslation> QuranTranslations { get; set; }


    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=URANUS\\DEV;Initial Catalog=forumisl_quran2;User ID=ils;Password=ils@123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
     
        OnModelCreating(modelBuilder);
    }

}