// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IslamicTragemContextHandeling.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace IslamicTragemContextHandeling.Core.NewModels;

public partial class forumisl_quran3Context : DbContext
{
    public forumisl_quran3Context()
    {
    }

    public forumisl_quran3Context(DbContextOptions<forumisl_quran3Context> options)
        : base(options)
    {
    }

    //public virtual DbSet<Sura> Suras { get; set; }
    //public virtual DbSet<Aya> Ayas { get; set; }
    //public virtual DbSet<QuranTranslation> QuranTranslations { get; set; }

    //public virtual DbSet<Category> Categories { get; set; }
    //public virtual DbSet<FixedPage> FixedPages { get; set; }
    //public virtual DbSet<News> News { get; set; }
    //public virtual DbSet<PaperLanguage> PaperLanguages { get; set; }
    //public virtual DbSet<SpecialistsCenter> SpecialistsCenters { get; set; }

    //public virtual DbSet<LibraryBook> LibraryBooks { get; set; }
    //public virtual DbSet<Paper> Papers { get; set; }
    //public virtual DbSet<Term> Terms { get; set; }
    //public virtual DbSet<HadithCategory> HadithCategories { get; set; }
    //public virtual DbSet<HadithChapter> HadithChapters { get; set; }

    //public virtual DbSet<HadithLanguage> HadithLanguages { get; set; }
    //public virtual DbSet<HadithBab> HadithBabs { get; set; }

    public virtual DbSet<Hadith> Hadiths { get; set; }
    public virtual DbSet<HadithTranslation> HadithTranslations { get; set; }





    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
         => optionsBuilder.UseSqlServer("Server=URANUS\\DEV;Database=IslamicTTFNew;User Id=ils;Password=ils@123;MultipleActiveResultSets=true;TrustServerCertificate=true;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}