// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("chapters")]
public  class HadithChapter
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [OldName("cat_id")]
    public int HadithCategoryId { get; set; } 
    public HadithCategory HadithCategory { get; set; }

    [OldName("chapter_id")]
    public int ChapterNo { get; set; } // check if this is chapter number in category ask abbas for this 




}