// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;


[OldName("cats")] 
public  class HadithCategory
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }


    [OldName("name")]
    [StringLength(255)]
    public string Name { get; set; }


    [OldName("full_name")]
    [StringLength(500)]
    public string FullName { get; set; }


    [OldName("cat_name_takhreej")]
    [StringLength(255)]
    public string CatNameTakhreej { get; set; }


    [OldName("writer")]
    public string Writer { get; set; }


    [OldName("full_writer_name")]
    public string FullWriterName { get; set; }


    [OldName("writer_death")]
    public string WriterDeath { get; set; }


    [OldName("about_book")]
    public string AboutBook { get; set; }


    [OldName("slug")]
    [StringLength(45)]
    public string Slug { get; set; }

    [OldName("definition")]
    public string Definition { get; set; }

    [OldName("rank")]
    public int Rank { get; set; }


    [OldName("chapter_rows")]
    [StringLength(200)]
    public string ChapterRows { get; set; }

    [OldName("cover_image")]
    public string CoverImage { get; set; }

    [OldName("category")]
    public int Category { get; set; }


    [OldName("start_id")]
    public int StartId { get; set; } //TODO: check if it referes to  start from Hadith Ids then delete it ? 

    [OldName("end_id")]
    public int EndId { get; set; } //TODO: check if it referes to  end from Hadith Ids then delete it ? 

    [OldName("death_year")]
    public int DeathYear { get; set; }


    [OldName("index_book")]
    [StringLength(200)]
    public string IndexBook { get; set; }

    [OldName("search_order")]
    public int SearchOrder { get; set; }


    [OldName("sound")]
    [StringLength(1000)]
    public string Sound { get; set; }

}