// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("bab")]
public partial class HadithBab
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("name")]
    public string Name { get; set; }


    [OldName("new_chapter_id")]
    public int ChapterId { get; set; } // references chapter(chapterId)
    [ForeignKey(nameof(ChapterId))]
    public HadithChapter Chapter { get; set; }

    [OldName("chapter_id")]
    public int ChapterNo { get; set; } // references chapter(chapterId)

    [OldName("cat_id")]
    public int CategoryId { get; set; } // TODO : Delete this column after handeling the relation with chapter 
    //public virtual Category Category { get; set; }

    [OldName("bab_id")]
    public int BabNo { get; set; }//TODO : check if this bab number in chapter



}
