// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("lang_hadith", Schema = "forumisl_quran2")]
[OldName("lang_hadith")]
public  class LangHadith
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [Required]
    [OldName("lang")]
    public string Lang { get; set; }
    //public virtual ICollection<Paper> Papers { get; set; }

}