// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;
[OldName("book")]
public  class LibraryBook
{ 
    // this is used for all the books  المكتبه or library module
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("title")]
    [StringLength(250)]
    public string Title { get; set; }

    //classified by category id 
    [OldName("cat_id")]
    public int CategoryId { get; set; } // this is a forign key for Category
    public virtual Category Category { get; set; }

    [OldName("author")]
    [StringLength(250)]
    public string Author { get; set; }

    [OldName("translator")]
    [StringLength(250)]
    public string Translator { get; set; }

    [OldName("source_lang")]
    [StringLength(250)]
    public string SourceLang { get; set; }

    [OldName("target_lang")]
    [StringLength(250)]
    public string TargetLang { get; set; }

    [OldName("publisher")]
    [StringLength(250)]
    public string Publisher { get; set; }

    [OldName("image")]
    [StringLength(250)]
    public string ImageUrl { get; set; }

    [OldName("description")]
    public string Description { get; set; }

    [OldName("download_link")]
    [StringLength(250)]
    public string DownloadLink { get; set; }

    [OldName("out_source")]
    [StringLength(500)]
    public string OutSource { get; set; }



    [OldName("view_count")]
    public int? ViewCount { get; set; }

    [OldName("download_count")]
    public int? DownloadCount { get; set; }

}