// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("marakez", Schema = "forumisl_quran2")]
[OldName("marakez")]
public  class Marakez
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("markaz_name")]
    public string MarkazName { get; set; }

    [OldName("country")]
    public string Country { get; set; }

    [OldName("markaz_location")]
    public string MarkazLocation { get; set; }

    [OldName("english_manager")]
    public string EnglishManager { get; set; }

    [OldName("phone")]
    [StringLength(112)]
    public string Phone { get; set; }

    [OldName("email")]
    [StringLength(30)]
    public string Email { get; set; }

    [OldName("website")]
    [StringLength(150)]
    public string Website { get; set; }

    [OldName("masarat")]
    public string Masarat { get; set; }

    public string Intag { get; set; }

    [OldName("view_count")]
    [StringLength(3000)]
    public string ViewCount { get; set; }

    //[OldName("download_count")]
    //[StringLength(3000)]
    //public string DownloadCount { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }
}