// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("news")]
public  class News //this is for Slider in the home page 
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("title")]
    public string Title { get; set; }

    [OldName("details")]
    public string Details { get; set; }

    [OldName("image")]
    [StringLength(500)]
    public string ImageUrl { get; set; }

}