// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("news", Schema = "forumisl_quran2")]
[OldName("news")]
public  class News
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("title")]
    public string Title { get; set; }

    [OldName("details")]
    public string Details { get; set; }

    [OldName("image")]
    [StringLength(500)]
    public string Image { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }
}