// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("papers")]
public  class Paper
{
    [Key]
    [OldName("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]

    public int Id { get; set; }

    [OldName("lang_id")]
    public int? PaperLanguageId { get; set; } // Foreign Key to LangHadith
    [ForeignKey(nameof(PaperLanguageId))]
    public virtual PaperLanguage PaperLanguage { get; set; }

    [OldName("paper_title")]
    public string Title { get; set; }

    [OldName("paper_type")]
    public string Type { get; set; }

    [OldName("paper_researcher")]
    public string ResearcherName { get; set; }

    [OldName("paper_admin")]
    public string AdminName { get; set; }

    [OldName("paper_date")]
    [StringLength(30)]
    public string Date { get; set; }

    [OldName("paper_location")]
    public string Location { get; set; }

    [OldName("pages_no")]
    [StringLength(30)]
    public string PagesNo { get; set; }

    [OldName("paper_summary")]
    public string Summary { get; set; }

    [OldName("paper_results")]
    public string Results { get; set; }


    [OldName("view_count")]
    [StringLength(3000)]
    public string ViewCount { get; set; } //TODO : should be int

}