// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("papers", Schema = "forumisl_quran2")]
[OldName("papers")]
public  class Paper
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("lang_id")]
    public int? LangId { get; set; } // Foreign Key to LangHadith

    [OldName("paper_title")]
    public string PaperTitle { get; set; }

    [OldName("paper_type")]
    public string PaperType { get; set; }

    [OldName("paper_researcher")]
    public string PaperResearcher { get; set; }

    [OldName("paper_admin")]
    public string PaperAdmin { get; set; }

    [OldName("paper_date")]
    [StringLength(30)]
    public string PaperDate { get; set; }

    [OldName("paper_location")]
    public string PaperLocation { get; set; }

    [OldName("pages_no")]
    [StringLength(30)]
    public string PagesNo { get; set; }

    [OldName("paper_summary")]
    public string PaperSummary { get; set; }

    [OldName("paper_results")]
    public string PaperResults { get; set; }

    //[OldName("other")]
    //[StringLength(50)]
    //public string Other { get; set; }

    //[OldName("image")]
    //[StringLength(250)]
    //public string Image { get; set; }

    [OldName("view_count")]
    [StringLength(3000)]
    public string ViewCount { get; set; }

    //[OldName("download_count")]
    //[StringLength(3000)]
    //public string DownloadCount { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }
    //[ForeignKey(nameof(LangId))]
    //public virtual LangHadith LangHadith { get; set; }
}