// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("papers", Schema = "forumisl_quran2")]
public  class Paper
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("lang_id")]
    public int? LangId { get; set; }

    [Column("paper_title")]
    public string PaperTitle { get; set; }

    [Column("paper_type")]
    public string PaperType { get; set; }

    [Column("paper_researcher")]
    public string PaperResearcher { get; set; }

    [Column("paper_admin")]
    public string PaperAdmin { get; set; }

    [Column("paper_date")]
    [StringLength(30)]
    public string PaperDate { get; set; }

    [Column("paper_location")]
    public string PaperLocation { get; set; }

    [Column("pages_no")]
    [StringLength(30)]
    public string PagesNo { get; set; }

    [Column("paper_summary")]
    public string PaperSummary { get; set; }

    [Column("paper_results")]
    public string PaperResults { get; set; }

    [Column("other")]
    [StringLength(50)]
    public string Other { get; set; }

    [Column("image")]
    [StringLength(250)]
    public string Image { get; set; }

    [Column("view_count")]
    [StringLength(3000)]
    public string ViewCount { get; set; }

    [Column("download_count")]
    [StringLength(3000)]
    public string DownloadCount { get; set; }

    [Column("status")]
    public int Status { get; set; }
}