// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("quran_translation", Schema = "forumisl_quran2")]
[OldName("quran_translation")]
public  class QuranTranslation
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("aya_id")]
    public int AyaId { get; set; }

    [OldName("sura_no")]
    [StringLength(9)]
    public string SuraNo { get; set; }

    [OldName("aya_no")]
    public int? AyaNo { get; set; }

    [OldName("translation_lang")]
    [StringLength(10)]
    public string TranslationLang { get; set; }

    [OldName("translation")]
    public string Translation { get; set; }

    [OldName("translator_name")]
    [StringLength(40)]
    public string TranslatorName { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }
    //public virtual Aya Aya { get; set; }
}