// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("quran_translation")]
public  class QuranTranslation
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("aya_id")]
    public int AyaId { get; set; }
    public virtual Aya Aya { get; set; }

    [OldName("translation_lang")]
    [StringLength(100)]
    public string LanguageName { get; set; } // there is a list in the website to select the language, store the values in this column

    [OldName("translation")]
    public string Translation { get; set; }

    [OldName("translator_name")]
    [StringLength(100)]
    public string TranslatorName { get; set; }

}