// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("marakez")]
public  class SpecialistsCenter 
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("markaz_name")]
    public string Name { get; set; }

    [OldName("country")]
    public string CountryName { get; set; }

    [OldName("markaz_location")]
    public string Location { get; set; }

    [OldName("english_manager")]
    public string ManagerName { get; set; }

    [OldName("phone")]
    [StringLength(112)]
    public string Phone { get; set; }

    [OldName("email")]
    [StringLength(30)]
    public string Email { get; set; }

    [OldName("website")]
    [StringLength(150)]
    public string WebsiteURL { get; set; }

    [OldName("masarat")]
    public string Masarat { get; set; }

    [OldName("Intag")]
    public string Intag { get; set; }

    [OldName("view_count")]
    [StringLength(3000)]
    public string ViewCount { get; set; }

}