// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("sura")]
public class Sura
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]

    [OldName("id")]
    public int Id { get; set; }

    [OldName("name")]
    [StringLength(50)]
    public string Name { get; set; }

    public  ICollection<Aya> Ayas { get; set; } = new List<Aya>();   


}