// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("sura", Schema = "forumisl_quran2")]
[Index("Id", Name = "sura$id", IsUnique = true)]
public  class Sura
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("sura_no")]
    public int? SuraNo { get; set; }

    [Column("name")]
    [StringLength(13)]
    public string Name { get; set; }
}