// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[OldName("term")]
public  class Term
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    [OldName("id")]

    public int Id { get; set; }

    [OldName("title")]
    [StringLength(300)]
    public string Title { get; set; }

    [OldName("meaning_lang")]
    [StringLength(700)]
    public string MeaningLanguage { get; set; }

    [OldName("meaning_term")]
    public string MeaningTerm { get; set; }


    [Required]
    [OldName("new_Cat_Id")]
    [StringLength(100)]
    public int? CategoryId { get; set; }  
    public Category? Category { get; set; }


    [OldName("voice_spell")]
    [StringLength(300)]
    public string VoiceSpell { get; set; }

    [OldName("en")]
    [StringLength(500)]
    public string English { get; set; }

    [OldName("fr")]
    [StringLength(600)]
    public string French { get; set; }

    [OldName("es")]
    [StringLength(500)]
    public string Spanish { get; set; }

    [OldName("en_synonyms")]
    [StringLength(500)]
    public string EnglishSynonyms { get; set; }

    [OldName("fr_synonyms")]
    [StringLength(500)]
    public string FrenchSynonyms { get; set; }

    [OldName("es_synonyms")]
    [StringLength(500)]
    public string SpanishSynonyms { get; set; }


    [OldName("view_count")]
    public int ViewCount { get; set; }


}
 