// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("term", Schema = "forumisl_quran2")]
[OldName("term")]
public  class Term
{
    [Key]
    [OldName("id")]
    public int Id { get; set; }

    [OldName("title")]
    [StringLength(300)]
    public string Title { get; set; }

    [OldName("meaning_lang")]
    [StringLength(700)]
    public string MeaningLang { get; set; }

    [OldName("meaning_term")]
    public string MeaningTerm { get; set; }

    [Required]
    [OldName("cat_id")]
    [StringLength(100)]
    public string CatId { get; set; }  

    [OldName("voice_spell")]
    [StringLength(300)]
    public string VoiceSpell { get; set; }

    [OldName("en")]
    [StringLength(500)]
    public string En { get; set; }

    [OldName("fr")]
    [StringLength(600)]
    public string Fr { get; set; }

    [OldName("es")]
    [StringLength(500)]
    public string Es { get; set; }

    [OldName("en_synonyms")]
    [StringLength(500)]
    public string EnSynonyms { get; set; }

    [OldName("fr_synonyms")]
    [StringLength(500)]
    public string FrSynonyms { get; set; }

    [OldName("es_synonyms")]
    [StringLength(500)]
    public string EsSynonyms { get; set; }

    [OldName("url")]
    [StringLength(300)]
    public string Url { get; set; }

    [OldName("page_html")]
    public string PageHtml { get; set; }

    [OldName("view_count")]
    public int ViewCount { get; set; }

    //[OldName("status")]
    //public int Status { get; set; }

    [Required]
    [OldName("cat_title")]
    public string CatTitle { get; set; } // create enum for this field or set as foreign key to Cat table
    //public virtual Cat Category { get; set; }
}
 