// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Core.NewModels;

[Table("term", Schema = "forumisl_quran2")]
public  class Term
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("title")]
    [StringLength(300)]
    public string Title { get; set; }

    [Column("meaning_lang")]
    [StringLength(700)]
    public string MeaningLang { get; set; }

    [Column("meaning_term")]
    public string MeaningTerm { get; set; }

    [Required]
    [Column("cat_id")]
    [StringLength(100)]
    public string CatId { get; set; }

    [Column("voice_spell")]
    [StringLength(300)]
    public string VoiceSpell { get; set; }

    [Column("en")]
    [StringLength(500)]
    public string En { get; set; }

    [Column("fr")]
    [StringLength(600)]
    public string Fr { get; set; }

    [Column("es")]
    [StringLength(500)]
    public string Es { get; set; }

    [Column("en_synonyms")]
    [StringLength(500)]
    public string EnSynonyms { get; set; }

    [Column("fr_synonyms")]
    [StringLength(500)]
    public string FrSynonyms { get; set; }

    [Column("es_synonyms")]
    [StringLength(500)]
    public string EsSynonyms { get; set; }

    [Column("url")]
    [StringLength(300)]
    public string Url { get; set; }

    [Column("page_html")]
    public string PageHtml { get; set; }

    [Column("view_count")]
    public int ViewCount { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Required]
    [Column("cat_title")]
    public string CatTitle { get; set; }
}