// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("aya", Schema = "forumisl_quran2")]
public partial class Aya
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("aya_id")]
    public int? AyaId { get; set; }

    [Required]
    [Column("aya")]
    public string Aya1 { get; set; }

    [Required]
    [Column("aya_no_tashkil")]
    public string AyaNoTashkil { get; set; }

    [Column("page_no")]
    public int? PageNo { get; set; }

    [Column("part_no")]
    public int? PartNo { get; set; }

    [Column("hezb_no")]
    public int HezbNo { get; set; }

    [Column("rob3_no")]
    public int Rob3No { get; set; }

    [Column("aya_no")]
    public int? AyaNo { get; set; }

    [Required]
    [Column("aya_no_ar")]
    public string AyaNoAr { get; set; }

    [Column("sura_no")]
    public int? SuraNo { get; set; }

    [Required]
    [Column("sura_name")]
    [StringLength(250)]
    public string SuraName { get; set; }

    [Column("wordCount")]
    public int WordCount { get; set; }

    [Column("view_count")]
    public int ViewCount { get; set; }
}