// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("books", Schema = "forumisl_quran2")]
public partial class Book1
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("book_id")]
    public int BookId { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Required]
    [Column("cover_image")]
    [StringLength(500)]
    public string CoverImage { get; set; }

    [Column("sort_menu")]
    public int SortMenu { get; set; }

    [Required]
    [Column("definition")]
    [StringLength(1000)]
    public string Definition { get; set; }

    [Column("status")]
    public int Status { get; set; }
}