// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("book", Schema = "forumisl_quran2")]
public partial class Book
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("title")]
    [StringLength(250)]
    public string Title { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("author")]
    [StringLength(250)]
    public string Author { get; set; }

    [Column("translator")]
    [StringLength(250)]
    public string Translator { get; set; }

    [Column("source_lang")]
    [StringLength(250)]
    public string SourceLang { get; set; }

    [Column("target_lang")]
    [StringLength(250)]
    public string TargetLang { get; set; }

    [Column("publisher")]
    [StringLength(250)]
    public string Publisher { get; set; }

    [Column("image")]
    [StringLength(250)]
    public string Image { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("download_link")]
    [StringLength(250)]
    public string DownloadLink { get; set; }

    [Column("out_source")]
    [StringLength(500)]
    public string OutSource { get; set; }

    [Column("url")]
    [StringLength(250)]
    public string Url { get; set; }

    [Column("inside_book_link")]
    [StringLength(500)]
    public string InsideBookLink { get; set; }

    [Column("page_html")]
    public string PageHtml { get; set; }

    [Column("view_count")]
    public int? ViewCount { get; set; }

    [Column("download_count")]
    public int? DownloadCount { get; set; }

    [Column("status")]
    public int Status { get; set; }
}