// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("cat", Schema = "forumisl_quran2")]
public partial class Cat
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("title_en")]
    [StringLength(100)]
    public string TitleEn { get; set; }

    [Column("title_ar")]
    [StringLength(100)]
    public string TitleAr { get; set; }

    [Column("description")]
    [StringLength(1000)]
    public string Description { get; set; }
}