// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("cats", Schema = "forumisl_quran2")]
public partial class Cat1
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [Column("full_name")]
    [StringLength(500)]
    public string FullName { get; set; }

    [Required]
    [Column("cat_name_takhreej")]
    [StringLength(255)]
    public string CatNameTakhreej { get; set; }

    [Required]
    [Column("writer")]
    public string Writer { get; set; }

    [Required]
    [Column("full_writer_name")]
    public string FullWriterName { get; set; }

    [Required]
    [Column("writer_death")]
    public string WriterDeath { get; set; }

    [Required]
    [Column("about_book")]
    public string AboutBook { get; set; }

    [Required]
    [Column("slug")]
    [StringLength(45)]
    public string Slug { get; set; }

    [Column("definition")]
    public string Definition { get; set; }

    [Column("rank")]
    public int Rank { get; set; }

    [Required]
    [Column("chapter_rows")]
    [StringLength(200)]
    public string ChapterRows { get; set; }

    [Required]
    [Column("date")]
    public string Date { get; set; }

    [Required]
    [Column("cover_image")]
    public string CoverImage { get; set; }

    [Column("category")]
    public int Category { get; set; }

    [Required]
    [Column("lang")]
    [StringLength(300)]
    public string Lang { get; set; }

    [Column("ver")]
    public int Ver { get; set; }

    [Column("start_id")]
    public int StartId { get; set; }

    [Column("end_id")]
    public int EndId { get; set; }

    [Column("death_year")]
    public int DeathYear { get; set; }

    [Required]
    [Column("index_book")]
    [StringLength(200)]
    public string IndexBook { get; set; }

    [Column("type_view")]
    public int TypeView { get; set; }

    [Column("priority")]
    public int Priority { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("search_order")]
    public int SearchOrder { get; set; }

    [Required]
    [Column("sound")]
    [StringLength(1000)]
    public string Sound { get; set; }

    [Required]
    [Column("multi")]
    [StringLength(1000)]
    public string Multi { get; set; }
}