// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("chapters_ttf", Schema = "forumisl_quran2")]
[Index("CatId", Name = "hadith_bab_id_idx")]
public partial class ChaptersTtf
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("tags")]
    [StringLength(255)]
    public string Tags { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("my_sort")]
    public int MySort { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("cron")]
    public int Cron { get; set; }
}