// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

public partial class forumisl_quran2Context : DbContext
{
    public forumisl_quran2Context()
    {
    }

    public forumisl_quran2Context(DbContextOptions<forumisl_quran2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Aya> Ayas { get; set; }

    public virtual DbSet<Bab> Babs { get; set; }

    public virtual DbSet<BabBokhary> BabBokharies { get; set; }

    public virtual DbSet<BabMuslim> BabMuslims { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<Book1> Books1 { get; set; }

    public virtual DbSet<Cat> Cats { get; set; }

    public virtual DbSet<Cat1> Cats1 { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<ChaptersBokhary> ChaptersBokharies { get; set; }

    public virtual DbSet<ChaptersMuslim> ChaptersMuslims { get; set; }

    public virtual DbSet<ChaptersTtf> ChaptersTtfs { get; set; }

    public virtual DbSet<FixedPage> FixedPages { get; set; }

    public virtual DbSet<HadithBokhary> HadithBokharies { get; set; }

    public virtual DbSet<HadithEnglish> HadithEnglishes { get; set; }

    public virtual DbSet<HadithFrench> HadithFrenches { get; set; }

    public virtual DbSet<HadithIndo> HadithIndos { get; set; }

    public virtual DbSet<HadithMuslim> HadithMuslims { get; set; }

    public virtual DbSet<HadithNew> HadithNews { get; set; }

    public virtual DbSet<HadithTranslation> HadithTranslations { get; set; }

    public virtual DbSet<HadithTranslationManage> HadithTranslationManages { get; set; }

    public virtual DbSet<HadithTranslationManage1> HadithTranslationManage1s { get; set; }

    public virtual DbSet<HrVacation> HrVacations { get; set; }

    public virtual DbSet<Lang> Langs { get; set; }

    public virtual DbSet<LangHadith> LangHadiths { get; set; }

    public virtual DbSet<LangWord> LangWords { get; set; }

    public virtual DbSet<Marakez> Marakezs { get; set; }

    public virtual DbSet<MeaningName> MeaningNames { get; set; }

    public virtual DbSet<News> News { get; set; }

    public virtual DbSet<NewsTest> NewsTests { get; set; }

    public virtual DbSet<Paper> Papers { get; set; }

    public virtual DbSet<PapersCat> PapersCats { get; set; }

    public virtual DbSet<QuranTranslation> QuranTranslations { get; set; }

    public virtual DbSet<ReportHadith> ReportHadiths { get; set; }

    public virtual DbSet<Sharh> Sharhs { get; set; }

    public virtual DbSet<SidbarMenu> SidbarMenus { get; set; }

    public virtual DbSet<SinglePage> SinglePages { get; set; }

    public virtual DbSet<Style> Styles { get; set; }

    public virtual DbSet<Sura> Suras { get; set; }

    public virtual DbSet<Taragem2> Taragem2s { get; set; }

    public virtual DbSet<Term> Terms { get; set; }

    public virtual DbSet<Tragem> Tragems { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=URANUS\\DEV;Initial Catalog=forumisl_quran2;User ID=ils;Password=ils@123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aya>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_aya_id");

            entity.Property(e => e.AyaId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.AyaNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PageNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PartNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraNo).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Bab>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_bab_id");
        });

        modelBuilder.Entity<BabBokhary>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_bab_bokhary_id");
        });

        modelBuilder.Entity<BabMuslim>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_bab_muslim_id");
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_book_id");

            entity.Property(e => e.Author).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.DownloadCount).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.DownloadLink).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Image).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.InsideBookLink).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.OutSource).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Publisher).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SourceLang).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.TargetLang).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Title).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Translator).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Url).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.ViewCount).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Book1>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_books_id");
        });

        modelBuilder.Entity<Cat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_cat_id");

            entity.Property(e => e.Description).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.TitleAr).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.TitleEn).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Cat1>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_cats_id");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_chapters_id");

            entity.Property(e => e.Tags).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<ChaptersBokhary>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_chapters_bokhary_id");

            entity.Property(e => e.Tags).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<ChaptersMuslim>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_chapters_muslim_id");

            entity.Property(e => e.Tags).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<ChaptersTtf>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_chapters_ttf_id");

            entity.Property(e => e.Tags).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<FixedPage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_fixed_pages_id");
        });

        modelBuilder.Entity<HadithBokhary>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_bokhary_id");

            entity.Property(e => e.LastViews).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SearchOrder).HasDefaultValue(1100);
            entity.Property(e => e.YusufTaraf).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<HadithEnglish>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_english_id");
        });

        modelBuilder.Entity<HadithFrench>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_french_id");
        });

        modelBuilder.Entity<HadithIndo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_indo_id");
        });

        modelBuilder.Entity<HadithMuslim>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_muslim_id");

            entity.Property(e => e.LastViews).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SearchOrder).HasDefaultValue(1100);
            entity.Property(e => e.YusufTaraf).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<HadithNew>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_new_id");

            entity.Property(e => e.LastViews).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SearchOrder).HasDefaultValue(1100);
            entity.Property(e => e.YusufTaraf).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<HadithTranslation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_translation_id");
        });

        modelBuilder.Entity<HadithTranslationManage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_translation_manage_id");
        });

        modelBuilder.Entity<HadithTranslationManage1>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hadith_translation_manage1_id");

            entity.Property(e => e.HadeethId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.HadeethTranslation).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.TranslationType).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<HrVacation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_hr_vacation_id");
        });

        modelBuilder.Entity<Lang>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_lang_id");

            entity.Property(e => e.DateCreat).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastUpdate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<LangHadith>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_lang_hadith_id");
        });

        modelBuilder.Entity<LangWord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_lang_word_id");

            entity.Property(e => e.DateCreat).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LastUpdate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Marakez>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_marakez_id");

            entity.Property(e => e.DownloadCount).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Email).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Phone).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.ViewCount).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Website).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<MeaningName>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_meaning_name_id");
        });

        modelBuilder.Entity<News>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_news_id");

            entity.Property(e => e.Image).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<NewsTest>(entity =>
        {
            entity.Property(e => e.Image).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Paper>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_papers_id");

            entity.Property(e => e.DownloadCount).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Image).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.LangId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Other).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PagesNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PaperDate).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.ViewCount).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<PapersCat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_papers_cat_id");
        });

        modelBuilder.Entity<QuranTranslation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_quran_translation_id");

            entity.Property(e => e.AyaNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.TranslationLang).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.TranslatorName).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<ReportHadith>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_report_hadith_id");

            entity.Property(e => e.DateSend).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Sharh>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_sharh_id");
        });

        modelBuilder.Entity<SidbarMenu>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_sidbar_menu_id");

            entity.Property(e => e.LastUpdate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<SinglePage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_single_page_id");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Style>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_styles_id");

            entity.Property(e => e.Status).HasDefaultValue((short)1);
        });

        modelBuilder.Entity<Sura>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_sura_id");

            entity.Property(e => e.Name).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraNo).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Taragem2>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_taragem2_id");
        });

        modelBuilder.Entity<Term>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_term_id");

            entity.Property(e => e.En).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.EnSynonyms).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Es).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.EsSynonyms).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Fr).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.FrSynonyms).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.MeaningLang).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Title).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Url).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.VoiceSpell).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Tragem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tragem_id");

            entity.Property(e => e.AyaNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PageNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.PartNo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.QuranId).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.SuraNo).HasDefaultValueSql("(NULL)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}