// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hadith_translation_manage1", Schema = "forumisl_quran2")]
public partial class HadithTranslationManage1
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("hadeeth_id")]
    public int? HadeethId { get; set; }

    [Column("translation_type")]
    [StringLength(7)]
    public string TranslationType { get; set; }

    [Column("hadeeth_translation")]
    public string HadeethTranslation { get; set; }
}