// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hadith_translation_manage", Schema = "forumisl_quran2")]
public partial class HadithTranslationManage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("hadeeth_id")]
    [StringLength(100)]
    public string HadeethId { get; set; }

    [Required]
    [Column("translation_type")]
    [StringLength(100)]
    public string TranslationType { get; set; }

    [Required]
    [Column("hadeeth_translation")]
    public string HadeethTranslation { get; set; }
}