// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hadith_english", Schema = "forumisl_quran2")]
public partial class HadithEnglish
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("hid")]
    public int Hid { get; set; }

    [Required]
    [Column("data")]
    public string Data { get; set; }

    [Required]
    [Column("rawy")]
    public string Rawy { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Required]
    [Column("rank")]
    [StringLength(10)]
    public string Rank { get; set; }

    [Required]
    [Column("hokm")]
    public string Hokm { get; set; }

    [Required]
    [Column("sound")]
    [StringLength(600)]
    public string Sound { get; set; }

    [Column("sunnah_id")]
    public int SunnahId { get; set; }

    [Column("selid")]
    public int Selid { get; set; }

    [Column("cat_id_old")]
    public int CatIdOld { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("lang")]
    public int Lang { get; set; }
}