// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hadith_new", Schema = "forumisl_quran2")]
[Index("CatId", Name = "cat_id")]
[Index("Id", Name = "hadith_new$yusuf_rawys", IsUnique = true)]
[Index("Selid", Name = "selid")]
public partial class HadithNew
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Required]
    [Column("m_hadtih")]
    public string MHadtih { get; set; }

    [Required]
    [Column("matn")]
    public string Matn { get; set; }

    [Column("h_id")]
    public int HId { get; set; }

    [Column("selid")]
    public int Selid { get; set; }

    [Column("uid")]
    public int Uid { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Required]
    [Column("search_txt")]
    public string SearchTxt { get; set; }

    [Column("rank")]
    public int Rank { get; set; }

    [Required]
    [Column("hokm")]
    public string Hokm { get; set; }

    [Required]
    [Column("shaker")]
    [StringLength(600)]
    public string Shaker { get; set; }

    [Column("sub_id")]
    public int SubId { get; set; }

    [Column("tab_id")]
    public int TabId { get; set; }

    [Required]
    [Column("nass")]
    public string Nass { get; set; }

    [Column("ver")]
    public int Ver { get; set; }

    [Column("rawy_id")]
    public int RawyId { get; set; }

    [Column("hid_old")]
    public int HidOld { get; set; }

    [Column("search_order")]
    public int SearchOrder { get; set; }

    [Column("word_menaing")]
    public int WordMenaing { get; set; }

    [Column("tarf")]
    public int Tarf { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("make_edit")]
    public int MakeEdit { get; set; }

    [Column("yusuf_taraf")]
    [StringLength(255)]
    public string YusufTaraf { get; set; }

    [Column("yusuf_matn")]
    public string YusufMatn { get; set; }

    [Column("hmp3")]
    public int Hmp3 { get; set; }

    [Column("sharh_mp3")]
    public short SharhMp3 { get; set; }

    [Column("view")]
    public int View { get; set; }

    [Column("last_views", TypeName = "datetime")]
    public DateTime LastViews { get; set; }

    [Column("wordCount")]
    public int WordCount { get; set; }
}