// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hadith_indo", Schema = "forumisl_quran2")]
public partial class HadithIndo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("hid")]
    public int Hid { get; set; }

    [Required]
    [Column("data")]
    public string Data { get; set; }

    [Column("book_id")]
    public int BookId { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("sunnah_id")]
    public int SunnahId { get; set; }

    [Column("selid")]
    public int Selid { get; set; }

    [Column("cat_id_old")]
    public int CatIdOld { get; set; }

    [Column("status")]
    public int Status { get; set; }
}