// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hadith_translation", Schema = "forumisl_quran2")]
public partial class HadithTranslation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("book_id")]
    [StringLength(100)]
    public string BookId { get; set; }

    [Required]
    [Column("volume_no")]
    [StringLength(100)]
    public string VolumeNo { get; set; }

    [Required]
    [Column("chapter_no")]
    [StringLength(100)]
    public string ChapterNo { get; set; }

    [Required]
    [Column("hadeeth_no")]
    [StringLength(100)]
    public string HadeethNo { get; set; }

    [Required]
    [Column("hadeeth")]
    public string Hadeeth { get; set; }

    [Required]
    [Column("title")]
    [StringLength(500)]
    public string Title { get; set; }

    [Required]
    [Column("hadeeth1")]
    public string Hadeeth1 { get; set; }

    [Column("status")]
    public int Status { get; set; }
}