// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("hr_vacation", Schema = "forumisl_quran2")]
public partial class HrVacation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("start_date")]
    public DateOnly StartDate { get; set; }

    [Column("end_date")]
    public DateOnly EndDate { get; set; }

    [Column("days_number")]
    public int DaysNumber { get; set; }

    [Required]
    [Column("description")]
    [StringLength(1000)]
    public string Description { get; set; }

    [Required]
    [Column("description_admin")]
    [StringLength(1000)]
    public string DescriptionAdmin { get; set; }

    [Column("admin_approve")]
    public int AdminApprove { get; set; }

    [Column("create_date")]
    [Precision(0)]
    public DateTime CreateDate { get; set; }

    [Column("user_add")]
    public int UserAdd { get; set; }

    [Column("status")]
    public short Status { get; set; }
}