// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("lang_hadith", Schema = "forumisl_quran2")]
public partial class LangHadith
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("lang")]
    public string Lang { get; set; }
}