// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("lang", Schema = "forumisl_quran2")]
public partial class Lang
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("lang")]
    [StringLength(200)]
    public string Lang1 { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("status_mobile")]
    public int StatusMobile { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [Column("date_creat", TypeName = "datetime")]
    public DateTime DateCreat { get; set; }

    [Required]
    [Column("logo_lang")]
    [StringLength(100)]
    public string LogoLang { get; set; }

    [Column("user_add")]
    public int UserAdd { get; set; }

    [Column("master_lang")]
    public int MasterLang { get; set; }

    [Required]
    [Column("filename")]
    [StringLength(20)]
    public string Filename { get; set; }

    [Required]
    [Column("direction")]
    [StringLength(5)]
    public string Direction { get; set; }
}