// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("lang_word", Schema = "forumisl_quran2")]
public partial class LangWord
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("word")]
    [StringLength(200)]
    public string Word { get; set; }

    [Column("lang")]
    public int Lang { get; set; }

    [Column("similar_word")]
    public int SimilarWord { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [Column("date_creat", TypeName = "datetime")]
    public DateTime DateCreat { get; set; }

    [Column("user_add")]
    public int UserAdd { get; set; }
}