// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("marakez", Schema = "forumisl_quran2")]
public partial class Marakez
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("markaz_name")]
    public string MarkazName { get; set; }

    [Column("country")]
    public string Country { get; set; }

    [Column("markaz_location")]
    public string MarkazLocation { get; set; }

    [Column("english_manager")]
    public string EnglishManager { get; set; }

    [Column("phone")]
    [StringLength(112)]
    public string Phone { get; set; }

    [Column("email")]
    [StringLength(30)]
    public string Email { get; set; }

    [Column("website")]
    [StringLength(150)]
    public string Website { get; set; }

    [Column("masarat")]
    public string Masarat { get; set; }

    public string Intag { get; set; }

    [Column("view_count")]
    [StringLength(3000)]
    public string ViewCount { get; set; }

    [Column("download_count")]
    [StringLength(3000)]
    public string DownloadCount { get; set; }

    [Column("status")]
    public int Status { get; set; }
}