// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("meaning_name", Schema = "forumisl_quran2")]
public partial class MeaningName
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("word_notashkeel")]
    [StringLength(500)]
    public string WordNotashkeel { get; set; }

    [Required]
    [Column("meaning")]
    [StringLength(1000)]
    public string Meaning { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("h_id")]
    public int HId { get; set; }

    [Column("selid")]
    public int Selid { get; set; }

    [Required]
    [Column("word_tashkeel")]
    [StringLength(200)]
    public string WordTashkeel { get; set; }

    [Required]
    [Column("cat_name")]
    [StringLength(200)]
    public string CatName { get; set; }

    [Required]
    [Column("bab_name")]
    [StringLength(500)]
    public string BabName { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Required]
    [Column("chapter_name")]
    [StringLength(500)]
    public string ChapterName { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Column("status")]
    public int Status { get; set; }
}