// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("news", Schema = "forumisl_quran2")]
public partial class News
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("title")]
    public string Title { get; set; }

    [Column("details")]
    public string Details { get; set; }

    [Column("image")]
    [StringLength(500)]
    public string Image { get; set; }

    [Column("status")]
    public int Status { get; set; }
}