// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("papers_cat", Schema = "forumisl_quran2")]
public partial class PapersCat
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("paper_lang")]
    public string PaperLang { get; set; }

    [Required]
    [Column("paper_lang_en")]
    public string PaperLangEn { get; set; }
}