// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("quran_translation", Schema = "forumisl_quran2")]
public partial class QuranTranslation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("aya_id")]
    public int AyaId { get; set; }

    [Column("sura_no")]
    [StringLength(9)]
    public string SuraNo { get; set; }

    [Column("aya_no")]
    public int? AyaNo { get; set; }

    [Column("translation_lang")]
    [StringLength(10)]
    public string TranslationLang { get; set; }

    [Column("translation")]
    public string Translation { get; set; }

    [Column("translator_name")]
    [StringLength(40)]
    public string TranslatorName { get; set; }

    [Column("status")]
    public int Status { get; set; }
}