// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("report_hadith", Schema = "forumisl_quran2")]
public partial class ReportHadith
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(500)]
    public string Name { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [Column("comment")]
    public string Comment { get; set; }

    [Required]
    [Column("url")]
    [StringLength(500)]
    public string Url { get; set; }

    [Column("selid")]
    public int Selid { get; set; }

    [Column("solved")]
    public short Solved { get; set; }

    [Column("status")]
    public short Status { get; set; }

    [Column("date_send", TypeName = "datetime")]
    public DateTime DateSend { get; set; }
}