// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("sharh", Schema = "forumisl_quran2")]
[Index("Hid", Name = "hid")]
public partial class Sharh
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("hid")]
    public int Hid { get; set; }

    [Column("uid")]
    public int Uid { get; set; }

    [Required]
    [Column("sharh")]
    public string Sharh1 { get; set; }

    [Column("book_id")]
    public int BookId { get; set; }

    [Required]
    [Column("search_txt")]
    public string SearchTxt { get; set; }

    [Column("sunnah_id")]
    public int SunnahId { get; set; }

    [Column("cat_id")]
    public int CatId { get; set; }

    [Column("selid")]
    public int Selid { get; set; }

    [Column("hadith_yes")]
    public int HadithYes { get; set; }

    [Required]
    [Column("name_book")]
    [StringLength(100)]
    public string NameBook { get; set; }

    [Column("chapter_id")]
    public int ChapterId { get; set; }

    [Column("bab_id")]
    public int BabId { get; set; }

    [Column("status")]
    public int Status { get; set; }
}