// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("sidbar_menu", Schema = "forumisl_quran2")]
public partial class SidbarMenu
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(1000)]
    public string Name { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("date_creat")]
    [Precision(0)]
    public DateTime DateCreat { get; set; }

    [Column("last_update", TypeName = "datetime")]
    public DateTime LastUpdate { get; set; }

    [Column("user_add")]
    public int UserAdd { get; set; }

    [Column("status_mobile")]
    public int StatusMobile { get; set; }

    [Required]
    [Column("link")]
    [StringLength(500)]
    public string Link { get; set; }

    [Required]
    [Column("link_target")]
    [StringLength(200)]
    public string LinkTarget { get; set; }

    [Required]
    [Column("icon")]
    [StringLength(500)]
    public string Icon { get; set; }

    [Column("sub_menu")]
    public int SubMenu { get; set; }

    [Column("permission")]
    public int Permission { get; set; }

    [Column("sort_menu")]
    public int SortMenu { get; set; }
}