// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("single_page", Schema = "forumisl_quran2")]
public partial class SinglePage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    public string Title { get; set; }

    [Required]
    [Column("content")]
    public string Content { get; set; }

    [Column("comment")]
    public short Comment { get; set; }

    [Required]
    [Column("photo")]
    [StringLength(255)]
    public string Photo { get; set; }

    [Column("user_add")]
    public int UserAdd { get; set; }

    [Column("lang")]
    public int Lang { get; set; }

    [Column("status")]
    public short Status { get; set; }

    [Column("larg_page")]
    public short LargPage { get; set; }

    [Required]
    [Column("description")]
    [StringLength(500)]
    public string Description { get; set; }

    [Column("create_date", TypeName = "datetime")]
    public DateTime CreateDate { get; set; }
}