// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("styles", Schema = "forumisl_quran2")]
public partial class Style
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [Column("path_files")]
    [StringLength(255)]
    public string PathFiles { get; set; }

    [Required]
    [Column("path_image")]
    [StringLength(255)]
    public string PathImage { get; set; }

    [Required]
    [Column("description")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("create_date")]
    [Precision(0)]
    public DateTime CreateDate { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Required]
    [Column("photo")]
    [StringLength(200)]
    public string Photo { get; set; }

    [Column("status")]
    public short Status { get; set; }
}