// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IslamicTragemContextHandeling.Models;

[Table("taragem2", Schema = "forumisl_quran2")]
[Index("Id", Name = "id")]
public partial class Taragem2
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("site_id")]
    public int SiteId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(250)]
    public string Name { get; set; }

    [Required]
    [Column("nickname")]
    [StringLength(250)]
    public string Nickname { get; set; }

    [Required]
    [Column("rotabah")]
    [StringLength(250)]
    public string Rotabah { get; set; }

    [Required]
    [Column("koniaa")]
    [StringLength(250)]
    public string Koniaa { get; set; }

    [Required]
    [Column("lakab")]
    [StringLength(250)]
    public string Lakab { get; set; }

    [Required]
    [Column("tabkaa")]
    [StringLength(250)]
    public string Tabkaa { get; set; }

    [Required]
    [Column("full_cv")]
    public string FullCv { get; set; }

    [Required]
    [Column("gorha_weadllah")]
    public string GorhaWeadllah { get; set; }

    [Required]
    [Column("shoikh")]
    public string Shoikh { get; set; }

    [Required]
    [Column("student")]
    public string Student { get; set; }

    [Required]
    [Column("kamal")]
    public string Kamal { get; set; }

    [Required]
    [Column("ikhamah")]
    [StringLength(1000)]
    public string Ikhamah { get; set; }

    [Required]
    [Column("ikrabaa")]
    [StringLength(1000)]
    public string Ikrabaa { get; set; }

    [Required]
    [Column("nasaab")]
    [StringLength(1000)]
    public string Nasaab { get; set; }

    [Required]
    [Column("mawaley")]
    [StringLength(1000)]
    public string Mawaley { get; set; }

    [Required]
    [Column("dead_where")]
    [StringLength(1000)]
    public string DeadWhere { get; set; }

    [Required]
    [Column("ikhtalet")]
    [StringLength(500)]
    public string Ikhtalet { get; set; }

    [Required]
    [Column("age_rawey")]
    [StringLength(500)]
    public string AgeRawey { get; set; }

    [Required]
    [Column("born_date")]
    [StringLength(500)]
    public string BornDate { get; set; }

    [Required]
    [Column("dead_date")]
    [StringLength(500)]
    public string DeadDate { get; set; }

    [Column("status")]
    public int Status { get; set; }
}